data:
  csv_path: ../Demo_Onnx/data/QA.csv
  encoding: cp874

index:
  corpus_pkl: ../Demo_Onnx/outputs/corpus_embeds.pkl

runtime:
  onnx_dir: ../Demo_Onnx/onnx_path
  tokenizer_dir: ../Demo_Onnx/onnx_path

feedback:
  csv_path: data/user_feedback.csv
